### ISSUE TITLE
C++ version of optim

### ISSUE THREAD

**Issue by lucasnell** [daijiang/phyr#14]
Not going from R to C++ for every bootstrap replicate would provide a pretty significant performance boost, so is there any interest in implementing a C++ optimizer instead of using R's optim function?

I wrote some code a while ago that used the multidimensional optimizer from GSL (link [here](https://www.gnu.org/software/gsl/doc/html/multimin.html)), and it worked pretty well. I used the Nelder-Mead version, but there are others available. There's also the [RcppNumerical](https://cran.r-project.org/web/packages/RcppNumerical/vignettes/introduction.html#numerical-optimization) package that contains the L-BFGS algorithm, but it uses RcppEigen, which I've found very difficult to use.

I've never gotten simulated annealing to work in C++, but I also haven't explored that many options.

**Comment by daijiang** [comment]
Hi @lucasnell , thanks for the pull request!

In terms of optim, I think both R's optim and nloptr::nlopt both were written in C. Just calling them within R will cost some time. At this moment, I still use them. I even [import them into c++ first](https://github.com/daijiang/phyr/blob/master/src/pglmm_gaussian.cpp#L261-L264), so that I can write all functions, including the optimization, within c++.  Not ideal, but I don't have the time or knowledge to figure out how to call them directly. 

A potential solution may be found in this discussion: https://github.com/jyypma/nloptr/issues/39 but again, I didn't have the time to figure out yet. If you are interested in, feel free to test it out and make another pull request!

Thanks!

**Comment by lucasnell** [comment]
Hey @daijiang , given the issues we've had with implementing the C++ version directly, are you okay closing this?

**Comment by daijiang** [comment]
Sure. It has been implemented in this [branch](https://github.com/daijiang/phyr/tree/cor_phylo_nlopt_cpp).
